### PR TITLE
TEST File for "fedimint-go"

### PR DESCRIPTION
**Pull request by PsychoPunkSage**
Added a demo tester function.... called `TestNewFedimintClient()` (will be adding more)....

### CODE REVIEW

**Comment by PsychoPunkSage** [comment]
@Kodylow 
I have implemented 1 tester function...
Can you please tell whether I'm writing testing scripts in correct way or not?
(I will add more tester functions but before that I want to make sure this is what you looking for in test Files)

Thank you

**Comment by Kodylow** [comment]
Good start, the more important parts to test are all of the http interactions, checking all the requests, responses, and types around them

**Comment by PsychoPunkSage** [comment]
Hi @Kodylow 
I'm facing an issue with fedimint-http... it is unable to build rocksdb...
image

While testing a tester function `TestWithdraw`(pushed) (http-interaction)...
I got this error::
```
jsonBody:  {"body":{"timeout":3600},"federationId":"federation123"}
Error creating deposit:  Post "http://localhost:3333/fedimint/v2/wallet/deposit-address": dial tcp 127.0.0.1:3333: connect: connection refused
jsonBody:  {"body":{"address":"UNKNOWN","amount_msat":"10000"},"federationId":"federation123"}
Error creating deposit:  Post "http://localhost:3333/fedimint/v2/wallet/withdraw": dial tcp 127.0.0.1:3333: connect: connection refused
```

Now how should I test it?? one way is to clone the repo inside `Fedimint-http` and then test it... but I don't want to do that... Like its lengthy, time consuming and will cause problems...
Is there any other way??

**Comment by Kodylow** [comment]
are you running that from inside nix develop? sometimes won't build rocks outside depending on your system

**Comment by PsychoPunkSage** [comment]
> are you running that from inside nix develop? sometimes won't build rocks outside depending on your system

Yeah, after typing `nix develop -i` > `just dev` it automatically starts compiling...

**Comment by Kodylow** [comment]
and within there it's still not compiling? what system are you running on?

**Comment by PsychoPunkSage** [comment]
I'm running it on Ubuntu 23.10

**Comment by Kodylow** [comment]
okay I was just able to compile a fresh one on a digital ocean box with ubuntu , can you try again with the new repo https://github.com/fedimint/fedimint-clientd and confirm it's still happening?

**Comment by PsychoPunkSage** [comment]
i'm getting this <br>
image

I think its not working

**Comment by Kodylow** [comment]
Is that fresh? Can you run `cargo clean`, pull from upstream, then run again?

**Comment by PsychoPunkSage** [comment]
> Is that fresh? Can you run `cargo clean`, pull from upstream, then run again?

No, same issue exist...
I did `cargo clean` > `nix develop -i` > `just dev`

**Comment by Kodylow** [comment]
okay this is fixed now on github.com/fedimint/fedimint-clientd, I wasn't pathing fedimint-clientd to use local multimint on 0.3

**Comment by PsychoPunkSage** [comment]
image
Same issue is comming again...
It says there is some issue regarding permission. Not sure what it means...

**Comment by Kodylow** [comment]
thats a separate issue. you've got a permissions issue with your shell, it doesn't let you create files. try running it with sudo.

Also I just moved all of the wrappers into fedimint-clientd can you move this over there

**Comment by PsychoPunkSage** [comment]
I think Now all the errors are gone...

Getting this
image

There is some issue regarding `NO Federation invite Code provided...`, Do I need to specify this in .env file?
My `.env` file::
```env
FEDIMINT_CLIENTD_INVITE_CODE = 'fed1...'
FEDIMINT_CLIENTD_DB_PATH = '/absolute/path/to/fm_db_dir'
FEDIMINT_CLIENTD_PASSWORD = 'some-secure-password-that-becomes-the-bearer-token'
FEDIMINT_CLIENTD_ADDR = '127.0.0.1:3333'
```
and 

Can you tell now how to use it to test the http request from `fedimint-go`

**Comment by Kodylow** [comment]
yes you need to set a .env or pass that in as a command line argument, and please switch to https://github.com/fedimint/fedimint-clientd , I moved fedimint-go into there as a wrapper to maintain everything across the different wrappers

**Comment by PsychoPunkSage** [comment]
Ok 
I have used the exact template provided in `env.example`.  I haven't changed the data either... Do i need to change the data of some fields??

>  moved fedimint-go into there as a wrapper to maintain everything across the different wrappers

Ok can you please tell how can I run the test (which I wrote) inside `clientd`? Like the command-line operations I need to do (if required) etc.

**Comment by Kodylow** [comment]
check how I did the `just test-ts`command in the JUSTFILE to run the typescript tests in clientd, closing this here please reopen in fedimint-clientd

**Pull request closed without merging**
